// eslint-disable-next-line import/prefer-default-export
export const BOOKLIST_REQUESTED = 'BOOKLIST_REQUESTED';
export const BOOKLIST_SUCCEEDED = 'BOOKLIST_SUCCEEDED';
export const BOOK_SELECT_REQUESTED = 'BOOK_SELECT_REQUESTED';
export const REGISTRATION_REQUESTED = 'REGISTRATION_REQUESTED';
