// eslint-disable-next-line import/prefer-default-export
export const BOOKLIST_REQUESTED = 'BOOKLIST_REQUESTED';
export const BOOKLIST_SUCCEEDED = 'BOOKLIST_SUCCEEDED';
export const NEW_BOOK_POST_REQUESTED = 'NEW_BOOK_POST_REQUESTED';
export const NEW_BOOK_POST_SUCCEEDED = 'NEW_BOOK_POST_SUCCEEDED';
export const BOOK_SELECT_REQUESTED = 'BOOK_SELECT_REQUESTED';
export const REGISTRATION_REQUESTED = 'REGISTRATION_REQUESTED';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
